services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      db-network:
        aliases:
          - db-internal
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-t', '10']
      interval: 10s
      timeout: 10s
      start_interval: 1s
      start_period: 1s
  db-studio:
    image: ghcr.io/drizzle-team/gateway:latest
    restart: always
    volumes:
      - drizzle-gateway:/app
    networks:
      - db-network
    environment:
      - STORE_PATH=/app
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    networks:
      - db-network
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:mysecretpassword@db-internal:5432/postgres}
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy

networks:
  db-network:

volumes:
  drizzle-gateway:
  db-data:
