packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@tanstack/react-form': ^1.19.1
  '@types/bun': ^1.2.20
  '@types/node': ^24.2.1
  better-auth: ^1.3.5
  hono: ^4.8.5
  lucide-react: ^0.525.0
  next-themes: ^0.4.6
  superjson: ^2.2.2
  type-fest: ^4.41.0
  typescript: 5.8.3
  use-intl: ^4.3.4
  zod: ^4.0.17
  zustand: ^5.0.6

catalogs:
  drizzle:
    '@types/pg': ^8.15.5
    drizzle-kit: beta
    drizzle-orm: beta
    drizzle-seed: beta
    pg: ^8.16.3
  react:
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
  tailwind:
    '@tailwindcss/vite': ^4.1.11
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.6
  trpc:
    '@tanstack/react-query': ^5.85.0
    '@trpc/client': ^11.4.4
    '@trpc/server': ^11.4.4
    '@trpc/tanstack-react-query': ^11.4.4
  vite:
    '@tanstack/react-router': ^1.131.7
    '@tanstack/react-router-ssr-query': ^1.131.7
    '@tanstack/react-start': ^1.131.7
    '@tanstack/router-plugin': ^1.131.7
    '@vitejs/plugin-react': ^4.7.0
    vite: ^7.1.2
    vite-tsconfig-paths: ^5.1.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

publicHoistPattern:
  - '*prettier*'
  - eslint
