packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@tanstack/react-form': ^1.14.1
  '@types/bun': ^1.2.19
  '@types/node': ^24.2.0
  better-auth: ^1.3.4
  hono: ^4.8.5
  lucide-react: ^0.536.0
  next-themes: ^0.4.6
  superjson: ^2.2.2
  type-fest: ^4.41.0
  typescript: 5.9.2
  use-intl: ^4.3.4
  zod: ^4.0.14
  zustand: ^5.0.6

catalogs:
  drizzle:
    '@types/pg': ^8.15.5
    drizzle-kit: 1.0.0-beta.1-c0277c0
    drizzle-orm: 1.0.0-beta.1-c0277c0
    pg: ^8.16.3
  react:
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
  tailwind:
    '@tailwindcss/vite': ^4.1.11
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.6
  trpc:
    '@tanstack/react-query': ^5.84.1
    '@trpc/client': ^11.4.4
    '@trpc/server': ^11.4.4
    '@trpc/tanstack-react-query': ^11.4.4
  vite:
    '@tanstack/react-router': ^1.130.12
    '@tanstack/react-router-with-query': ^1.130.12
    '@tanstack/react-start': ^1.130.15
    '@tanstack/router-plugin': ^1.130.15
    '@vitejs/plugin-react': ^4.7.0
    vite: ^7.0.6
    vite-tsconfig-paths: ^5.1.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

publicHoistPattern:
  - '*prettier*'
  - eslint
